post http://127.0.0.16/register.php

{"username": "user1", "password": "pass123"}

###
post http://127.0.0.16/login.php

{"username": "user1", "password": "pass123"}

###
post http://127.0.0.16/add_task.php

{
    "token": "aeecfbe3c407e10849722432630fbbe197f0496aa48e489ceae48af501d4b499", 
    "title": "Nueva tarea", 
    "description": "Descripción de la tarea"
}

###
post http://127.0.0.16/delete_task.php
{"token": "10d756bd0ef4ef4477b1f289f7e38d08cc295d91b9c3f82999cf1fdf77603fcc", "task_id": 1}

###
post http://127.0.0.16/edit_task.php

{"token": "10d756bd0ef4ef4477b1f289f7e38d08cc295d91b9c3f82999cf1fdf77603fcc", "task_id": 1, "title": "Tarea actualizada", "description": "Descripción actualizada"}


###
post http://127.0.0.16/list_tasks.php

{
	"token": "aeecfbe3c407e10849722432630fbbe197f0496aa48e489ceae48af501d4b499"
}

